import '@/app/resources/css/globals.css'
import NavLink from '@/app/util/NavLink';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// CM에 관련된 Nav를 동적으로 생성

// 만들어진 tab contllor를 가져와야 함

export default function DashboardLayout({
  children, // will be a page or nested layout
}: {
  children: React.ReactNode;
}) {
  return (
			<div>
				<header className="border-b p-4">
					<nav className="space-x-4">
						<NavLink href="/mom/CM/BOM">BOM</NavLink>
					</nav>
				</header>
				<div className="p-4">{children}</div>
			</div>
  )
}
