import './../page.module.css'
import NavLink from '../util/NavLink';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// Root Nav를 DB에서 받아서 동적으로 생성해야함

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
			<div>
				<header className="border-b p-4">
					<nav className="space-x-4">
						<NavLink href="/">Home</NavLink>
						<NavLink href="/mom">MOM DashBoard</NavLink>
						<NavLink href="/auth">Signin</NavLink>
						<NavLink href="/mom/CM">CM</NavLink>
					</nav>
				</header>
				<div className="p-4">{children}</div>
			</div>
  )
}
