import '@/resources/css/globals.css'
import NavLink from '@/util/NavLink';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// Root Nav를 DB에서 받아서 동적으로 생성해야함

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {




  return (
			<div>
				<header className="border-b p-4">
					<aside>
					<nav className="space-x-1">
						<NavLink href="/">Home</NavLink>
						<NavLink href="/auth">Signin</NavLink>
						<div>CM</div>
						<div>MM</div>
						<div>PR</div>
					</nav>
					</aside>
				</header>
				<section>
					<nav className="space-x-4">
						<div>CM1</div>
						<div>CM2</div>
						<div>CM3</div>
						<div>CM4</div>
					</nav>
					<div className="p-4">{children}</div>
				</section>
			</div>
  )
}
