import '@/resources/css/globals.css'
import NavLink from '@/util/NavLink';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
			<div>
				<header className="border-b p-4">
					<nav className="space-x-4">
						<NavLink href="/mom">DashBoard</NavLink>
					</nav>
				</header>
				<div className="p-4">{children}</div>
			</div>
  )
}
