import Providers from './providers'
import CheckSession from '@/components/CheckSession/page'

export const metadata = {
  title: "Next-Auth Tutorial",
  description: "Generated by Sakura Dev",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <CheckSession>
            {children}
          </CheckSession>
        </Providers>
      </body>
    </html>
  );
}